export interface FlyDangerousTelemetry {
  flyDangerousTelemetryId: number;
  packetId: number;
  gameVersion: string;
  currentGameMode: string;
  currentLevelName: string;
  currentMusicTrackName: string;
  currentShipName: string;
  playerName: string;
  playerFlagIso: string;
  currentPlayerCount: number;
  shipWorldPosition: { x: number; y: number; z: number };
  shipAltitude: number;
  shipHeightFromGround: number;
  shipSpeed: number;
  accelerationMagnitudeNormalised: number;
  gForce: number;
  pitchPosition: number;
  rollPosition: number;
  yawPosition: number;
  throttlePosition: number;
  lateralHPosition: number;
  lateralVPosition: number;
  boostCapacitorPercent: number;
  boostTimerReady: boolean;
  boostChargeReady: boolean;
  underWater: boolean;
  lightsActive: boolean;
  velocityLimiterActive: boolean;
  vectorFlightAssistActive: boolean;
  rotationalFlightAssistActive: boolean;
  proximityWarning: boolean;
  proximityWarningSeconds: number;
  collisionThisFrame: boolean;
  collisionStartedThisFrame: boolean;
  collisionImpactNormalised: number;
  collisionDirection: { x: number; y: number; z: number };
  isBoostSpooling: boolean;
  boostSpoolStartedThisFrame: boolean;
  isBoostThrustActive: boolean;
  boostThrustStartedThisFrame: boolean;
  boostSpoolTotalDurationSeconds: number;
  boostThrustTotalDurationSeconds: number;
  boostThrustProgressNormalised: number;
  shipShakeNormalised: number;
  currentLateralVelocity: { x: number; y: number; z: number };
  currentLateralForce: { x: number; y: number; z: number };
  currentAngularVelocity: { x: number; y: number; z: number };
  currentAngularTorque: { x: number; y: number; z: number };
  currentLateralVelocityNormalised: { x: number; y: number; z: number };
  currentLateralForceNormalised: { x: number; y: number; z: number };
  currentAngularVelocityNormalised:  { x: number; y: number; z: number };
  currentAngularTorqueNormalised:  { x: number; y: number; z: number };
  shipWorldRotationEuler:  { x: number; y: number; z: number };
  maxSpeed: number;
}
